server:
  port: 8000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: method_route
          uri: lb://user-service
          predicates:
            - Path=/banking/u
            - Method=GET
          filters:
            - RewritePath=/banking/u, /test

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka